Rails.application.routes.draw do
  root 'top#new'
  resources :top
  get 'end' => 'top#end'
  # hackのルーティング
  get 'hackstep1' => 'hack#step1'
  get 'hackstep2' => 'hack#step2'
  get 'hackstep3' => 'hack#step3'
  get 'hackstep4' => 'hack#step4'
  get 'hackstep5' => 'hack#step5'
  get 'hackstep6' => 'hack#step6'
  get 'hackstep7' => 'hack#step7'
  get 'hackstep8' => 'hack#step8'
  get 'hackstep9' => 'hack#step9'
  get 'hackstep10' => 'hack#step10'
  get 'hackstep11' => 'hack#step11'
  get 'hackstep12' => 'hack#step12'
  get 'hackstep13' => 'hack#step13'
  get 'hackstep14' => 'hack#step14'
  # leakのルーティング
  get 'leakstep1' => 'leak#step1'
  get 'leakstep2' => 'leak#step2'
  get 'leakstep3' => 'leak#step3'
  get 'leakstep4' => 'leak#step4'
  get 'leakstep5' => 'leak#step5'
  get 'leakstep6' => 'leak#step6'
  get 'leakstep7' => 'leak#step7'
  get 'leakstep8' => 'leak#step8'
  get 'leakstep9' => 'leak#step9'
  get 'leakstep10' => 'leak#step10'
  get 'leakstep11' => 'leak#step11'
  get 'leakstep12' => 'leak#step12'
  get 'leakstep13' => 'leak#step13'
  get 'leakstep14' => 'leak#step14'
end
